export const locales = {
  en: { code: 'en', locale: 'en-US', hreflang: 'en', label: 'EN', marketPath: '/market/', hubPath: '/guides/', hubLabel: 'Guides', homeLabel: 'Home', helpLabel: 'Help', privacyLabel: 'Privacy', appLabel: 'Get App', marketLabel: 'Live Market', marketHubTitle: 'Live Precious Metals Prices', marketHubIntro: 'Track real-time prices for gold, silver, platinum, and palladium.', marketOverviewLabel: 'Market context', ctaLabel: 'Get the App Free', disclosure: 'MyGoldFolio provides tracking tools, not investment, legal, or tax advice.', consentPrompt: 'Enable functional cookies to view the interactive TradingView chart.', relatedGuide: 'Read our portfolio tracking guide' },
  de: { code: 'de', locale: 'de-DE', hreflang: 'de', label: 'DE', marketPath: '/de/market/', hubPath: '/de/ratgeber/', hubLabel: 'Wissen', homeLabel: 'Startseite', helpLabel: 'Hilfe', privacyLabel: 'Datenschutz', appLabel: 'App holen', marketLabel: 'Live Markt', marketHubTitle: 'Live Edelmetallpreise', marketHubIntro: 'Verfolge Echtzeitpreise für Gold, Silber, Platin und Palladium.', marketOverviewLabel: 'Marktkontext', ctaLabel: 'App kostenlos laden', disclosure: 'MyGoldFolio bietet Tracking-Werkzeuge, keine Anlage-, Rechts- oder Steuerberatung.', consentPrompt: 'Aktiviere funktionale Cookies, um den interaktiven TradingView-Chart zu sehen.', relatedGuide: 'Lies unseren Portfolio-Tracking-Guide' },
  fr: { code: 'fr', locale: 'fr-FR', hreflang: 'fr', label: 'FR', marketPath: '/fr/market/', hubPath: '/fr/guides/', hubLabel: 'Guides', homeLabel: 'Accueil', helpLabel: 'Aide', privacyLabel: 'Confidentialité', appLabel: 'Obtenir l\'app', marketLabel: 'Marché en direct', marketHubTitle: 'Prix des métaux précieux en direct', marketHubIntro: 'Suivez les prix en temps réel de l\'or, l\'argent, le platine et le palladium.', marketOverviewLabel: 'Contexte du marché', ctaLabel: 'Télécharger l\'App gratuitement', disclosure: 'MyGoldFolio fournit des outils de suivi, pas des conseils d’investissement, juridiques ou fiscaux.', consentPrompt: 'Activez les cookies fonctionnels pour voir le graphique interactif TradingView.', relatedGuide: 'Lisez notre guide de suivi de portefeuille' },
  tr: { code: 'tr', locale: 'tr-TR', hreflang: 'tr', label: 'TR', marketPath: '/tr/market/', hubPath: '/tr/rehber/', hubLabel: 'Rehber', homeLabel: 'Ana sayfa', helpLabel: 'Yardım', privacyLabel: 'Gizlilik', appLabel: 'Uygulamayı edin', marketLabel: 'Canlı Piyasa', marketHubTitle: 'Canlı Değerli Maden Fiyatları', marketHubIntro: 'Altın, gümüş, platin ve paladyum için gerçek zamanlı fiyatları takip edin.', marketOverviewLabel: 'Piyasa bağlamı', ctaLabel: 'Uygulamayı ücretsiz indir', disclosure: 'MyGoldFolio takip araçları sunar; yatırım, hukuk veya vergi tavsiyesi vermez.', consentPrompt: 'Etkileşimli TradingView grafiğini görmek için işlevsel çerezleri etkinleştirin.', relatedGuide: 'Portföy takip rehberimizi okuyun' },
  es: { code: 'es', locale: 'es-ES', hreflang: 'es', label: 'ES', marketPath: '/es/market/', hubPath: '/es/guias/', hubLabel: 'Guías', homeLabel: 'Inicio', helpLabel: 'Ayuda', privacyLabel: 'Privacidad', appLabel: 'Obtener app', marketLabel: 'Mercado en vivo', marketHubTitle: 'Precios de metales preciosos en vivo', marketHubIntro: 'Sigue los precios en tiempo real del oro, la plata, el platino y el paladio.', marketOverviewLabel: 'Contexto del mercado', ctaLabel: 'Descargar App gratis', disclosure: 'MyGoldFolio ofrece herramientas de seguimiento, no asesoramiento de inversión, legal ni fiscal.', consentPrompt: 'Activa las cookies funcionales para ver el gráfico interactivo de TradingView.', relatedGuide: 'Lee nuestra guía de seguimiento de cartera' },
  it: { code: 'it', locale: 'it-IT', hreflang: 'it', label: 'IT', marketPath: '/it/market/', hubPath: '/it/guide/', hubLabel: 'Guide', homeLabel: 'Home', helpLabel: 'Aiuto', privacyLabel: 'Privacy', appLabel: 'Ottieni app', marketLabel: 'Mercato in tempo reale', marketHubTitle: 'Prezzi dei metalli preziosi in tempo reale', marketHubIntro: 'Monitora i prezzi in tempo reale di oro, argento, platino e palladio.', marketOverviewLabel: 'Contesto di mercato', ctaLabel: 'Scarica l\'App gratis', disclosure: 'MyGoldFolio offre strumenti di monitoraggio, non consulenza finanziaria, legale o fiscale.', consentPrompt: 'Abilita i cookie funzionali per visualizzare il grafico interattivo di TradingView.', relatedGuide: 'Leggi la nostra guida al monitoraggio del portafoglio' },
  pt: { code: 'pt', locale: 'pt-BR', hreflang: 'pt-BR', label: 'PT-BR', marketPath: '/pt/market/', hubPath: '/pt/guias/', hubLabel: 'Guias', homeLabel: 'Início', helpLabel: 'Ajuda', privacyLabel: 'Privacidade', appLabel: 'Obter app', marketLabel: 'Mercado ao vivo', marketHubTitle: 'Preços de metais preciosos ao vivo', marketHubIntro: 'Acompanhe os preços em tempo real de ouro, prata, platina e paládio.', marketOverviewLabel: 'Contexto do mercado', ctaLabel: 'Baixar App grátis', disclosure: 'MyGoldFolio oferece ferramentas de acompanhamento, não aconselhamento de investimento, jurídico ou tributário.', consentPrompt: 'Ative os cookies funcionais para ver o gráfico interativo do TradingView.', relatedGuide: 'Leia nosso guia de acompanhamento de carteira' }
};

export const metals = [
  {
    id: 'gold',
    symbol: 'GOLD',
    tvSymbol: 'OANDA:XAUUSD',
    theme: 'gold',
    locales: {
      en: { title: 'Live Gold Price Chart', description: 'Track the live gold price and view historical charts. Use MyGoldFolio to manage your physical gold investments offline.', seoTitle: 'Live Gold Price Chart | MyGoldFolio', ctaTitle: 'Track your gold portfolio' },
      de: { title: 'Live Goldpreis-Chart', description: 'Verfolge den aktuellen Goldpreis und betrachte historische Charts. Nutze MyGoldFolio, um deine physischen Goldinvestitionen offline zu verwalten.', seoTitle: 'Live Goldpreis-Chart | MyGoldFolio', ctaTitle: 'Verfolge dein Gold-Portfolio' },
      fr: { title: 'Graphique du cours de l\'or en direct', description: 'Suivez le prix de l\'or en direct et consultez les graphiques historiques. Utilisez MyGoldFolio pour gérer vos investissements en or physique hors ligne.', seoTitle: 'Graphique du cours de l\'or en direct | MyGoldFolio', ctaTitle: 'Suivez votre portefeuille d\'or' },
      tr: { title: 'Canlı Altın Fiyatı Grafiği', description: 'Canlı altın fiyatını takip edin ve geçmiş grafikleri görüntüleyin. Fiziksel altın yatırımlarınızı çevrimdışı yönetmek için MyGoldFolio\'yu kullanın.', seoTitle: 'Canlı Altın Fiyatı Grafiği | MyGoldFolio', ctaTitle: 'Altın portföyünüzü takip edin' },
      es: { title: 'Gráfico del precio del oro en vivo', description: 'Sigue el precio del oro en vivo y visualiza gráficos históricos. Usa MyGoldFolio para gestionar tus inversiones en oro físico sin conexión.', seoTitle: 'Gráfico del precio del oro en vivo | MyGoldFolio', ctaTitle: 'Haz un seguimiento de tu cartera de oro' },
      it: { title: 'Grafico del prezzo dell\'oro in tempo reale', description: 'Tieni traccia del prezzo dell\'oro in tempo reale e visualizza i grafici storici. Usa MyGoldFolio per gestire i tuoi investimenti in oro fisico offline.', seoTitle: 'Grafico del prezzo dell\'oro in tempo reale | MyGoldFolio', ctaTitle: 'Monitora il tuo portafoglio in oro' },
      pt: { title: 'Gráfico do preço do ouro ao vivo', description: 'Acompanhe o preço do ouro ao vivo e veja gráficos históricos. Use o MyGoldFolio para gerenciar seus investimentos em ouro físico offline.', seoTitle: 'Gráfico do preço do ouro ao vivo | MyGoldFolio', ctaTitle: 'Acompanhe sua carteira de ouro' }
    }
  },
  {
    id: 'silver',
    symbol: 'SILVER',
    tvSymbol: 'OANDA:XAGUSD',
    theme: 'slate',
    locales: {
      en: { title: 'Live Silver Price Chart', description: 'Track the live silver price and view historical charts. Keep an eye on the gold-silver ratio and manage your physical silver stack securely offline.', seoTitle: 'Live Silver Price Chart | MyGoldFolio', ctaTitle: 'Track your silver portfolio' },
      de: { title: 'Live Silberpreis-Chart', description: 'Verfolge den aktuellen Silberpreis und betrachte historische Charts. Behalte das Gold-Silber-Ratio im Auge und verwalte deinen Silberbestand sicher offline.', seoTitle: 'Live Silberpreis-Chart | MyGoldFolio', ctaTitle: 'Verfolge dein Silber-Portfolio' },
      fr: { title: 'Graphique du cours de l\'argent en direct', description: 'Suivez le prix de l\'argent en direct et consultez les graphiques historiques. Gardez un œil sur le ratio or-argent et gérez votre argent physique hors ligne en toute sécurité.', seoTitle: 'Graphique du cours de l\'argent en direct | MyGoldFolio', ctaTitle: 'Suivez votre portefeuille d\'argent' },
      tr: { title: 'Canlı Gümüş Fiyatı Grafiği', description: 'Canlı gümüş fiyatını takip edin ve geçmiş grafikleri görüntüleyin. Altın-gümüş oranını göz önünde bulundurun ve fiziksel gümüş birikiminizi güvenle çevrimdışı yönetin.', seoTitle: 'Canlı Gümüş Fiyatı Grafiği | MyGoldFolio', ctaTitle: 'Gümüş portföyünüzü takip edin' },
      es: { title: 'Gráfico del precio de la plata en vivo', description: 'Sigue el precio de la plata en vivo y visualiza gráficos históricos. Presta atención a la relación oro-plata y gestiona tu plata física de forma segura sin conexión.', seoTitle: 'Gráfico del precio de la plata en vivo | MyGoldFolio', ctaTitle: 'Haz un seguimiento de tu cartera de plata' },
      it: { title: 'Grafico del prezzo dell\'argento in tempo reale', description: 'Tieni traccia del prezzo dell\'argento in tempo reale e visualizza i grafici storici. Tieni d\'occhio il rapporto oro-argento e gestisci il tuo argento fisico offline in modo sicuro.', seoTitle: 'Grafico del prezzo dell\'argento in tempo reale | MyGoldFolio', ctaTitle: 'Monitora il tuo portafoglio in argento' },
      pt: { title: 'Gráfico do preço da prata ao vivo', description: 'Acompanhe o preço da prata ao vivo e veja gráficos históricos. Fique de olho na relação ouro-prata e gerencie sua prata física com segurança offline.', seoTitle: 'Gráfico do preço da prata ao vivo | MyGoldFolio', ctaTitle: 'Acompanhe sua carteira de prata' }
    }
  },
  {
    id: 'platinum',
    symbol: 'PLATINUM',
    tvSymbol: 'OANDA:XPTUSD',
    theme: 'teal',
    locales: {
      en: { title: 'Live Platinum Price Chart', description: 'Track the live platinum price and view historical charts. Monitor industrial demand and manage your physical platinum investments offline with MyGoldFolio.', seoTitle: 'Live Platinum Price Chart | MyGoldFolio', ctaTitle: 'Track your platinum portfolio' },
      de: { title: 'Live Platinpreis-Chart', description: 'Verfolge den aktuellen Platinpreis und betrachte historische Charts. Überwache die industrielle Nachfrage und verwalte deine physischen Platininvestitionen offline.', seoTitle: 'Live Platinpreis-Chart | MyGoldFolio', ctaTitle: 'Verfolge dein Platin-Portfolio' },
      fr: { title: 'Graphique du cours du platine en direct', description: 'Suivez le prix du platine en direct et consultez les graphiques historiques. Surveillez la demande industrielle et gérez vos investissements en platine physique hors ligne.', seoTitle: 'Graphique du cours du platine en direct | MyGoldFolio', ctaTitle: 'Suivez votre portefeuille de platine' },
      tr: { title: 'Canlı Platin Fiyatı Grafiği', description: 'Canlı platin fiyatını takip edin ve geçmiş grafikleri görüntüleyin. Endüstriyel talebi izleyin ve fiziksel platin yatırımlarınızı çevrimdışı yönetin.', seoTitle: 'Canlı Platin Fiyatı Grafiği | MyGoldFolio', ctaTitle: 'Platin portföyünüzü takip edin' },
      es: { title: 'Gráfico del precio del platino en vivo', description: 'Sigue el precio del platino en vivo y visualiza gráficos históricos. Supervisa la demanda industrial y gestiona tus inversiones en platino físico sin conexión.', seoTitle: 'Gráfico del precio del platino en vivo | MyGoldFolio', ctaTitle: 'Haz un seguimiento de tu cartera de platino' },
      it: { title: 'Grafico del prezzo del platino in tempo reale', description: 'Tieni traccia del prezzo del platino in tempo reale e visualizza i grafici storici. Monitora la domanda industriale e gestisci i tuoi investimenti in platino fisico offline.', seoTitle: 'Grafico del prezzo del platino in tempo reale | MyGoldFolio', ctaTitle: 'Monitora il tuo portafoglio in platino' },
      pt: { title: 'Gráfico do preço da platina ao vivo', description: 'Acompanhe o preço da platina ao vivo e veja gráficos históricos. Monitore a demanda industrial e gerencie seus investimentos em platina física offline.', seoTitle: 'Gráfico do preço da platina ao vivo | MyGoldFolio', ctaTitle: 'Acompanhe sua carteira de platina' }
    }
  },
  {
    id: 'palladium',
    symbol: 'PALLADIUM',
    tvSymbol: 'OANDA:XPDUSD',
    theme: 'indigo',
    locales: {
      en: { title: 'Live Palladium Price Chart', description: 'Track the live palladium price and view historical charts. Stay updated on market movements and manage your physical palladium offline.', seoTitle: 'Live Palladium Price Chart | MyGoldFolio', ctaTitle: 'Track your palladium portfolio' },
      de: { title: 'Live Palladiumpreis-Chart', description: 'Verfolge den aktuellen Palladiumpreis und betrachte historische Charts. Bleibe über Marktbewegungen informiert und verwalte dein physisches Palladium offline.', seoTitle: 'Live Palladiumpreis-Chart | MyGoldFolio', ctaTitle: 'Verfolge dein Palladium-Portfolio' },
      fr: { title: 'Graphique du cours du palladium en direct', description: 'Suivez le prix du palladium en direct et consultez les graphiques historiques. Restez informé des mouvements du marché et gérez votre palladium physique hors ligne.', seoTitle: 'Graphique du cours du palladium en direct | MyGoldFolio', ctaTitle: 'Suivez votre portefeuille de palladium' },
      tr: { title: 'Canlı Paladyum Fiyatı Grafiği', description: 'Canlı paladyum fiyatını takip edin ve geçmiş grafikleri görüntüleyin. Piyasa hareketlerinden haberdar olun ve fiziksel paladyumunuzu çevrimdışı yönetin.', seoTitle: 'Canlı Paladyum Fiyatı Grafiği | MyGoldFolio', ctaTitle: 'Paladyum portföyünüzü takip edin' },
      es: { title: 'Gráfico del precio del paladio en vivo', description: 'Sigue el precio del paladio en vivo y visualiza gráficos históricos. Mantente actualizado sobre los movimientos del mercado y gestiona tu paladio físico sin conexión.', seoTitle: 'Gráfico del precio del paladio en vivo | MyGoldFolio', ctaTitle: 'Haz un seguimiento de tu cartera de paladio' },
      it: { title: 'Grafico del prezzo del palladio in tempo reale', description: 'Tieni traccia del prezzo del palladio in tempo reale e visualizza i grafici storici. Tieniti aggiornato sui movimenti del mercato e gestisci il tuo palladio fisico offline.', seoTitle: 'Grafico del prezzo del palladio in tempo reale | MyGoldFolio', ctaTitle: 'Monitora il tuo portafoglio in palladio' },
      pt: { title: 'Gráfico do preço do paládio ao vivo', description: 'Acompanhe o preço do paládio ao vivo e veja gráficos históricos. Fique por dentro dos movimentos do mercado e gerencie seu paládio físico offline.', seoTitle: 'Gráfico do preço do paládio ao vivo | MyGoldFolio', ctaTitle: 'Acompanhe sua carteira de paládio' }
    }
  }
];

// Localized editorial context for every market route (W3). These paragraphs explain
// reference pricing, dealer spreads, and the limits of tax interpretation without
// presenting the page as investment, legal, or tax advice.
export const marketCommentary = {
  gold: {
    en: { title: 'Gold market context', overview: 'Gold is traded globally and is commonly compared by fine weight. The live reference chart helps you see the direction of the market, while your own purchase records show what your specific bars, coins, or jewellery actually cost.', spread: 'A spot reference is not a dealer buy or sell quote. Premiums, fabrication, shipping, storage, and the dealer spread can move your break-even price well away from the chart, especially for small units.', tax: 'Tax treatment for physical gold depends on your country, product, holding period, and circumstances. Keep invoices and sale records together, then confirm any filing question with the relevant local authority or a qualified adviser.' },
    de: { title: 'Marktkontext für Gold', overview: 'Gold wird weltweit gehandelt und meist nach Feingewicht verglichen. Der Live-Referenzchart zeigt die Marktrichtung; deine eigenen Käufe zeigen, was deine Barren, Münzen oder Schmuckstücke tatsächlich gekostet haben.', spread: 'Ein Spot-Referenzpreis ist kein Ankaufs- oder Verkaufspreis eines Händlers. Aufgeld, Herstellung, Versand, Lagerung und Händlerspanne können deinen Break-even deutlich vom Chart entfernen, besonders bei kleinen Einheiten.', tax: 'Die steuerliche Behandlung von physischem Gold hängt von Land, Produkt, Haltedauer und deiner Situation ab. Bewahre Rechnungen und Verkaufsbelege zusammen auf und kläre konkrete Fragen mit Finanzamt oder Steuerberatung.' },
    fr: { title: 'Contexte du marché de l’or', overview: 'L’or est négocié dans le monde entier et se compare généralement selon son poids fin. Le graphique de référence montre la direction du marché ; vos propres achats indiquent le coût réel de vos lingots, pièces ou bijoux.', spread: 'Un cours spot de référence n’est pas un prix d’achat ou de vente chez un professionnel. Prime, fabrication, livraison, stockage et marge du négociant peuvent éloigner votre seuil de rentabilité du graphique, surtout pour les petites unités.', tax: 'La fiscalité de l’or physique dépend du pays, du produit, de la durée de détention et de votre situation. Conservez factures et ventes ensemble et demandez confirmation à l’administration compétente ou à un conseiller qualifié.' },
    tr: { title: 'Altın piyasa bağlamı', overview: 'Altın dünya çapında işlem görür ve genellikle saf ağırlık üzerinden karşılaştırılır. Canlı referans grafiği piyasanın yönünü gösterir; kendi kayıtlarınız ise külçe, sikke veya mücevherinizin gerçek maliyetini gösterir.', spread: 'Spot referans fiyatı bir satıcının alış veya satış teklifi değildir. Primler, üretim, kargo, saklama ve satıcı marjı, özellikle küçük birimlerde başa baş fiyatınızı grafikten uzaklaştırabilir.', tax: 'Fiziki altının vergi uygulaması ülkeye, ürüne, elde tutma süresine ve kişisel durumunuza bağlıdır. Faturaları ve satış kayıtlarını saklayın; bildirim sorularını ilgili kurum veya uzman danışmanla doğrulayın.' },
    es: { title: 'Contexto del mercado del oro', overview: 'El oro se negocia en todo el mundo y suele compararse por peso fino. El gráfico de referencia en vivo ayuda a ver la dirección del mercado, mientras tus registros muestran cuánto costaron realmente tus lingotes, monedas o joyas.', spread: 'Una referencia spot no es una cotización de compra o venta de un comerciante. Las primas, fabricación, envío, custodia y margen del distribuidor pueden alejar bastante tu punto de equilibrio del gráfico, sobre todo en unidades pequeñas.', tax: 'La fiscalidad del oro físico depende del país, producto, plazo de tenencia y circunstancias personales. Conserva juntos facturas y ventas y confirma cualquier declaración con la autoridad local o un asesor cualificado.' },
    it: { title: 'Contesto del mercato dell’oro', overview: 'L’oro è scambiato in tutto il mondo e viene spesso confrontato in base al peso fino. Il grafico di riferimento mostra la direzione del mercato; i tuoi registri indicano quanto sono costati davvero lingotti, monete o gioielli.', spread: 'Un riferimento spot non è una quotazione di acquisto o vendita del commerciante. Premi, lavorazione, spedizione, custodia e margine possono allontanare il tuo break-even dal grafico, soprattutto per i piccoli formati.', tax: 'Il trattamento fiscale dell’oro fisico dipende da Paese, prodotto, periodo di possesso e situazione personale. Conserva insieme fatture e vendite e verifica ogni obbligo con l’autorità locale o un consulente qualificato.' },
    pt: { title: 'Contexto do mercado de ouro', overview: 'O ouro é negociado globalmente e costuma ser comparado pelo peso fino. O gráfico de referência ao vivo mostra a direção do mercado, enquanto seus registros indicam o custo real de suas barras, moedas ou joias.', spread: 'Uma referência spot não é uma cotação de compra ou venda de um comerciante. Ágios, fabricação, frete, custódia e margem do revendedor podem afastar bastante seu ponto de equilíbrio do gráfico, sobretudo em unidades pequenas.', tax: 'A tributação do ouro físico depende do país, produto, prazo de posse e circunstâncias pessoais. Guarde notas fiscais e vendas juntas e confirme qualquer obrigação com a autoridade local ou um profissional qualificado.' }
  },
  silver: {
    en: { title: 'Silver market context', overview: 'Silver combines precious-metal demand with substantial industrial use, so its reference price can move differently from gold. Compare the chart with the fine weight and exact product details recorded in your portfolio.', spread: 'Silver products often carry premiums and, in some markets, taxes that are material relative to the metal value. A low spot price alone does not tell you the delivered cost or the price needed to break even.', tax: 'Tax and reporting rules for physical silver vary widely and may differ from gold. Keep purchase, delivery, and sale documents, and use local professional guidance for a transaction-specific answer.' },
    de: { title: 'Marktkontext für Silber', overview: 'Silber verbindet Edelmetallnachfrage mit umfangreicher industrieller Nutzung und kann sich deshalb anders als Gold bewegen. Vergleiche den Chart mit Feingewicht und den genauen Produktdaten in deinem Portfolio.', spread: 'Silberprodukte haben oft Aufgelder und in manchen Märkten Steuern, die im Verhältnis zum Metallwert erheblich sind. Ein niedriger Spotpreis sagt allein nichts über Lieferkosten oder deinen Break-even aus.', tax: 'Steuer- und Meldepflichten für physisches Silber unterscheiden sich stark und können von Gold abweichen. Bewahre Kauf-, Liefer- und Verkaufsbelege auf und nutze für konkrete Fälle lokale Steuerberatung.' },
    fr: { title: 'Contexte du marché de l’argent', overview: 'L’argent répond à la fois à une demande de métal précieux et à une forte demande industrielle ; son cours de référence peut donc évoluer différemment de celui de l’or. Comparez le graphique au poids fin et au produit enregistré.', spread: 'Les produits en argent comportent souvent des primes et, selon le marché, des taxes importantes par rapport à la valeur du métal. Un spot bas ne suffit pas à connaître le coût livré ni le seuil de rentabilité.', tax: 'Les règles fiscales et déclaratives de l’argent physique varient beaucoup et peuvent différer de celles de l’or. Conservez les documents d’achat, de livraison et de vente et demandez un avis local pour un cas concret.' },
    tr: { title: 'Gümüş piyasa bağlamı', overview: 'Gümüş, değerli maden talebini yüksek sanayi kullanımıyla birleştirir; bu nedenle referans fiyatı altından farklı hareket edebilir. Grafiği, portföyünüzdeki saf ağırlık ve ürün bilgileriyle karşılaştırın.', spread: 'Gümüş ürünlerinde primler ve bazı pazarlarda metal değerine göre önemli vergiler bulunabilir. Düşük spot fiyatı tek başına teslim maliyetinizi veya başa baş noktanızı göstermez.', tax: 'Fiziki gümüşün vergi ve bildirim kuralları ülkeden ülkeye değişir ve altından farklı olabilir. Alış, teslimat ve satış belgelerini saklayın; somut işlemler için yerel bir uzmandan görüş alın.' },
    es: { title: 'Contexto del mercado de la plata', overview: 'La plata combina la demanda de metal precioso con un uso industrial importante, por lo que su referencia puede moverse de forma distinta al oro. Compara el gráfico con el peso fino y el producto exacto de tu cartera.', spread: 'Los productos de plata suelen llevar primas y, en algunos mercados, impuestos relevantes frente al valor del metal. Un spot bajo no basta para saber el coste entregado ni el precio de equilibrio.', tax: 'Las reglas fiscales y de declaración de la plata física varían mucho y pueden diferir de las del oro. Conserva documentos de compra, entrega y venta y consulta un profesional local para un caso concreto.' },
    it: { title: 'Contesto del mercato dell’argento', overview: 'L’argento unisce la domanda di metallo prezioso a un uso industriale rilevante, quindi il suo riferimento può muoversi diversamente dall’oro. Confronta il grafico con peso fino e prodotto registrato.', spread: 'I prodotti in argento spesso hanno premi e, in alcuni mercati, imposte rilevanti rispetto al valore del metallo. Uno spot basso non indica da solo il costo consegnato o il prezzo di pareggio.', tax: 'Le regole fiscali e dichiarative sull’argento fisico variano molto e possono differire da quelle dell’oro. Conserva documenti di acquisto, consegna e vendita e chiedi un parere locale per il caso specifico.' },
    pt: { title: 'Contexto do mercado de prata', overview: 'A prata combina a demanda por metal precioso com um uso industrial significativo, por isso seu preço de referência pode se mover de forma diferente do ouro. Compare o gráfico com o peso fino e o produto registrado.', spread: 'Produtos de prata costumam ter ágio e, em alguns mercados, impostos relevantes em relação ao valor do metal. Um spot baixo não informa sozinho o custo entregue nem o preço de equilíbrio.', tax: 'As regras fiscais e de declaração da prata física variam bastante e podem ser diferentes das do ouro. Guarde documentos de compra, entrega e venda e confirme casos concretos com um profissional local.' }
  },
  platinum: {
    en: { title: 'Platinum market context', overview: 'Platinum is both a precious metal and an industrial input, with supply and automotive demand influencing its market. Use the reference chart for context and keep the purity, weight, and product form of each holding separate.', spread: 'Dealer spreads can be wider for platinum than for frequently traded gold products, and availability varies by market. The chart is a neutral reference; it does not include fabrication, delivery, or resale conditions.', tax: 'The tax treatment of physical platinum is jurisdiction-specific and product-dependent. Keep a complete cost basis and sale trail, and obtain local advice before relying on a tax assumption.' },
    de: { title: 'Marktkontext für Platin', overview: 'Platin ist Edelmetall und industrieller Rohstoff zugleich; Angebot und die Nachfrage aus der Autoindustrie beeinflussen den Markt. Nutze den Referenzchart zur Einordnung und erfasse Reinheit, Gewicht und Produktform getrennt.', spread: 'Händlerspannen können bei Platin größer sein als bei häufig gehandelten Goldprodukten, und die Verfügbarkeit variiert. Der Chart ist eine neutrale Referenz und enthält weder Herstellung noch Lieferung oder Wiederverkaufsbedingungen.', tax: 'Die Besteuerung von physischem Platin hängt von Land und Produkt ab. Führe eine vollständige Anschaffungskosten- und Verkaufshistorie und hole vor einer konkreten Annahme lokale Beratung ein.' },
    fr: { title: 'Contexte du marché du platine', overview: 'Le platine est à la fois un métal précieux et une matière première industrielle ; l’offre et la demande automobile influencent son marché. Utilisez le graphique comme repère et séparez titre, poids et forme de chaque produit.', spread: 'Les marges peuvent être plus larges pour le platine que pour les produits en or très négociés, et la disponibilité varie selon le marché. Le graphique est une référence neutre sans fabrication, livraison ni conditions de revente.', tax: 'La fiscalité du platine physique dépend du pays et du produit. Conservez une base de coût et un historique de vente complets et demandez un avis local avant toute conclusion fiscale.' },
    tr: { title: 'Platin piyasa bağlamı', overview: 'Platin hem değerli bir maden hem de sanayi girdisidir; arz ve otomotiv talebi piyasayı etkiler. Referans grafiğini bağlam için kullanın ve her varlığın saflık, ağırlık ve ürün biçimini ayrı tutun.', spread: 'Platin satıcı marjları, sık işlem gören altın ürünlerinden daha geniş olabilir ve bulunabilirlik pazara göre değişir. Grafik tarafsız bir referanstır; üretim, teslimat veya yeniden satış koşullarını içermez.', tax: 'Fiziki platinin vergi uygulaması ülkeye ve ürüne bağlıdır. Eksiksiz maliyet ve satış kaydı tutun; vergi varsayımına güvenmeden önce yerel uzman görüşü alın.' },
    es: { title: 'Contexto del mercado del platino', overview: 'El platino es un metal precioso y también un insumo industrial; la oferta y la demanda automovilística influyen en su mercado. Usa el gráfico como referencia y separa pureza, peso y formato de cada posición.', spread: 'Los márgenes pueden ser más amplios en platino que en productos de oro muy negociados, y la disponibilidad cambia según el mercado. El gráfico es una referencia neutral y no incluye fabricación, entrega ni condiciones de reventa.', tax: 'La fiscalidad del platino físico depende del país y del producto. Mantén completa la base de coste y el historial de ventas y busca asesoramiento local antes de tomar una conclusión fiscal.' },
    it: { title: 'Contesto del mercato del platino', overview: 'Il platino è sia un metallo prezioso sia un input industriale; offerta e domanda automobilistica influenzano il mercato. Usa il grafico come riferimento e separa purezza, peso e forma del prodotto.', spread: 'I margini possono essere più ampi per il platino rispetto ai prodotti d’oro molto scambiati e la disponibilità varia per mercato. Il grafico è un riferimento neutro e non include lavorazione, consegna o condizioni di rivendita.', tax: 'Il trattamento fiscale del platino fisico dipende da Paese e prodotto. Conserva una base di costo e una cronologia delle vendite complete e chiedi consulenza locale prima di fare affidamento su un’ipotesi fiscale.' },
    pt: { title: 'Contexto do mercado de platina', overview: 'A platina é um metal precioso e também um insumo industrial; a oferta e a demanda automotiva influenciam seu mercado. Use o gráfico como referência e mantenha separados pureza, peso e formato de cada posição.', spread: 'As margens podem ser maiores na platina do que em produtos de ouro muito negociados, e a disponibilidade varia por mercado. O gráfico é uma referência neutra e não inclui fabricação, entrega ou condições de revenda.', tax: 'A tributação da platina física depende do país e do produto. Mantenha a base de custo e o histórico de vendas completos e procure orientação local antes de confiar numa conclusão fiscal.' }
  },
  palladium: {
    en: { title: 'Palladium market context', overview: 'Palladium pricing is influenced by industrial demand, recycling, and supply conditions as well as precious-metal sentiment. A reference chart gives market context; your portfolio records remain the source for your own exposure and cost basis.', spread: 'Palladium products can be less liquid and have wider dealer spreads than mainstream bullion. Compare the reference level with actual premiums, delivery costs, and the realistic resale quote for the product you own.', tax: 'Rules for physical palladium are especially dependent on local classification and transaction details. Preserve invoices and sale records and ask a qualified local adviser before making a tax or reporting decision.' },
    de: { title: 'Marktkontext für Palladium', overview: 'Der Palladiumpreis wird neben der Stimmung für Edelmetalle von Industrienachfrage, Recycling und Angebotsbedingungen beeinflusst. Der Referenzchart ordnet den Markt ein; dein Portfolio bleibt die Quelle für eigenes Engagement und Anschaffungskosten.', spread: 'Palladiumprodukte können weniger liquide sein und größere Händlerspannen haben als gängiges Anlagegold. Vergleiche das Referenzniveau mit Aufgeld, Lieferkosten und dem realistischen Ankaufspreis deines konkreten Produkts.', tax: 'Die Regeln für physisches Palladium hängen besonders von lokaler Einordnung und Transaktionsdetails ab. Bewahre Rechnungen und Verkaufsbelege auf und hole vor einer Steuer- oder Meldeentscheidung qualifizierte Beratung ein.' },
    fr: { title: 'Contexte du marché du palladium', overview: 'Le prix du palladium dépend de la demande industrielle, du recyclage et de l’offre, autant que du sentiment sur les métaux précieux. Le graphique donne le contexte ; vos registres restent la source de votre exposition et de votre coût.', spread: 'Les produits en palladium peuvent être moins liquides et avoir des marges plus larges que les lingots courants. Comparez le niveau de référence aux primes, à la livraison et au prix de reprise réaliste du produit détenu.', tax: 'Les règles applicables au palladium physique dépendent fortement de la classification locale et de la transaction. Conservez factures et ventes et demandez conseil avant toute décision fiscale ou déclarative.' },
    tr: { title: 'Paladyum piyasa bağlamı', overview: 'Paladyum fiyatı, değerli maden duyarlılığının yanı sıra sanayi talebi, geri dönüşüm ve arz koşullarından etkilenir. Referans grafik piyasa bağlamı sağlar; kendi riskiniz ve maliyetiniz için portföy kayıtlarınız esas kaynaktır.', spread: 'Paladyum ürünleri, yaygın külçelere göre daha düşük likiditeye ve daha geniş satıcı marjlarına sahip olabilir. Referans seviyeyi gerçek prim, teslimat maliyeti ve ürününüzün makul geri alım teklifiyle karşılaştırın.', tax: 'Fiziki paladyum kuralları yerel sınıflandırmaya ve işlem ayrıntılarına özellikle bağlıdır. Faturaları ve satış kayıtlarını saklayın; vergi veya bildirim kararı öncesi yetkin bir yerel danışmana başvurun.' },
    es: { title: 'Contexto del mercado del paladio', overview: 'El precio del paladio depende de la demanda industrial, el reciclaje y la oferta, además del sentimiento sobre los metales preciosos. El gráfico aporta contexto; tus registros son la fuente de tu exposición y coste.', spread: 'Los productos de paladio pueden tener menos liquidez y márgenes más amplios que el bullion habitual. Compara el nivel de referencia con primas, entrega y la cotización realista de recompra de tu producto.', tax: 'Las reglas del paladio físico dependen especialmente de la clasificación local y los detalles de la operación. Conserva facturas y ventas y consulta a un profesional antes de decidir sobre impuestos o declaraciones.' },
    it: { title: 'Contesto del mercato del palladio', overview: 'Il prezzo del palladio è influenzato da domanda industriale, riciclo e condizioni dell’offerta, oltre che dal sentiment sui metalli preziosi. Il grafico offre contesto; i tuoi registri restano la fonte per esposizione e costo.', spread: 'I prodotti in palladio possono essere meno liquidi e avere margini più ampi rispetto ai lingotti comuni. Confronta il riferimento con premi, costi di consegna e quotazione realistica di riacquisto del prodotto posseduto.', tax: 'Le regole sul palladio fisico dipendono in particolare dalla classificazione locale e dai dettagli della transazione. Conserva fatture e vendite e chiedi un parere qualificato prima di decidere su imposte o dichiarazioni.' },
    pt: { title: 'Contexto do mercado de paládio', overview: 'O preço do paládio é influenciado pela demanda industrial, reciclagem e condições de oferta, além do sentimento sobre metais preciosos. O gráfico oferece contexto; seus registros são a fonte da sua exposição e base de custo.', spread: 'Produtos de paládio podem ter menos liquidez e margens maiores do que o bullion comum. Compare o nível de referência com ágio, custo de entrega e a cotação realista de recompra do produto que você possui.', tax: 'As regras para paládio físico dependem especialmente da classificação local e dos detalhes da transação. Preserve notas fiscais e vendas e procure orientação qualificada antes de decidir sobre impostos ou declarações.' }
  }
};

export function marketPath(metal, locale) {
  const base = locale.code === 'en' ? '/market/' : `/${locale.code}/market/`;
  return `${base}${metal.id}/`;
}

// ── Live-chart configuration (audit W1 / WEB-UX2) ──────────────────────────
// Reference currencies are USD + EUR only (mirror the app's native currencies).
// English defaults to USD/troy-ounce; other locales to EUR/gram. Visitors switch
// instruments via the widget (allow_symbol_change); a deep link may override with
// ?currency=USD|EUR & ?unit=g|ozt — any other value falls back to the page default.
export const marketChartConfig = {
  en: { tvLocale: 'en', currency: 'USD', unit: 'ozt', consentButton: 'Accept cookies', note: 'Live reference chart. Use the toolbar to change the currency or unit.', unavailable: 'Chart temporarily unavailable. Please try again later.' },
  de: { tvLocale: 'de', currency: 'EUR', unit: 'g', consentButton: 'Cookies akzeptieren', note: 'Live-Referenzchart. Ändere Währung oder Einheit über die Symbolleiste.', unavailable: 'Chart derzeit nicht verfügbar. Bitte versuche es später erneut.' },
  fr: { tvLocale: 'fr', currency: 'EUR', unit: 'g', consentButton: 'Accepter les cookies', note: 'Graphique de référence en direct. Modifiez la devise ou l’unité via la barre d’outils.', unavailable: 'Graphique momentanément indisponible. Réessayez plus tard.' },
  tr: { tvLocale: 'tr', currency: 'EUR', unit: 'g', consentButton: 'Çerezleri kabul et', note: 'Canlı referans grafiği. Para birimini veya birimi araç çubuğundan değiştirin.', unavailable: 'Grafik geçici olarak kullanılamıyor. Lütfen daha sonra tekrar deneyin.' },
  es: { tvLocale: 'es', currency: 'EUR', unit: 'g', consentButton: 'Aceptar cookies', note: 'Gráfico de referencia en vivo. Cambia la moneda o la unidad en la barra de herramientas.', unavailable: 'Gráfico no disponible temporalmente. Inténtalo de nuevo más tarde.' },
  it: { tvLocale: 'it', currency: 'EUR', unit: 'g', consentButton: 'Accetta i cookie', note: 'Grafico di riferimento live. Cambia valuta o unità dalla barra degli strumenti.', unavailable: 'Grafico temporaneamente non disponibile. Riprova più tardi.' },
  pt: { tvLocale: 'br', currency: 'EUR', unit: 'g', consentButton: 'Aceitar cookies', note: 'Gráfico de referência ao vivo. Altere a moeda ou a unidade na barra de ferramentas.', unavailable: 'Gráfico temporariamente indisponível. Tente novamente mais tarde.' },
};

const TV_BASE = { gold: 'XAU', silver: 'XAG', platinum: 'XPT', palladium: 'XPD' };

// USD & EUR reference feeds only. Bare symbols (verified to resolve); gram feeds are not OANDA.
// XPT/XPD EUR-gram (XPTEURG/XPDEURG) are best-effort — if a feed is missing the resolver falls
// back to EUR-ounce, then USD-ounce, so a page never renders a dead symbol.
const TV_SYMBOLS = {
  XAU: { 'USD:ozt': 'XAUUSD', 'USD:g': 'XAUUSDG', 'EUR:ozt': 'XAUEUR', 'EUR:g': 'XAUEURG' },
  XAG: { 'USD:ozt': 'XAGUSD', 'USD:g': 'XAGUSDG', 'EUR:ozt': 'XAGEUR', 'EUR:g': 'XAGEURG' },
  XPT: { 'USD:ozt': 'XPTUSD', 'USD:g': 'XPTUSDG', 'EUR:ozt': 'XPTEUR', 'EUR:g': 'XPTEURG' },
  XPD: { 'USD:ozt': 'XPDUSD', 'USD:g': 'XPDUSDG', 'EUR:ozt': 'XPDEUR', 'EUR:g': 'XPDEURG' },
};

export function tvSymbolsFor(metal) {
  return TV_SYMBOLS[TV_BASE[metal.id] || 'XAU'];
}
