export const locales = {
  en: { code: 'en', locale: 'en-US', label: 'EN', hubPath: '/guides/', articlePath: '/guides/track-precious-metals-portfolio/', hubLabel: 'Guides', eyebrow: 'Practical knowledge for precious metals', hubTitle: 'Your precious-metals portfolio. Clearly in view.', hubIntro: 'Practical guides for recording, understanding, and organizing Gold, Silver, and other precious-metal holdings.', latestLabel: 'Latest guide', readLabel: 'Read guide', backLabel: 'Guides', homeLabel: 'Home', helpLabel: 'Help', privacyLabel: 'Privacy', appLabel: 'Get the app', contentsLabel: 'In this guide', relatedLabel: 'More to explore', faqLabel: 'Frequently asked questions', disclosure: 'MyGoldFolio provides tracking tools, not investment, legal, or tax advice.' },
  de: { code: 'de', locale: 'de-DE', label: 'DE', hubPath: '/de/ratgeber/', articlePath: '/de/ratgeber/edelmetalle-portfolio-tracken/', hubLabel: 'Wissen', eyebrow: 'Praxiswissen für Edelmetalle', hubTitle: 'Dein Edelmetall-Portfolio. Klar im Blick.', hubIntro: 'Praktische Guides zum Erfassen, Bewerten und Organisieren von Gold, Silber und weiteren Edelmetallen.', latestLabel: 'Aktueller Guide', readLabel: 'Guide lesen', backLabel: 'Wissen', homeLabel: 'Startseite', helpLabel: 'Hilfe', privacyLabel: 'Datenschutz', appLabel: 'App holen', contentsLabel: 'In diesem Guide', relatedLabel: 'Mehr entdecken', faqLabel: 'Häufige Fragen', disclosure: 'MyGoldFolio bietet Tracking-Werkzeuge, keine Anlage-, Rechts- oder Steuerberatung.' },
  fr: { code: 'fr', locale: 'fr-FR', label: 'FR', hubPath: '/fr/guides/', articlePath: '/fr/guides/suivre-portefeuille-metaux-precieux/', hubLabel: 'Guides', eyebrow: 'Conseils pratiques sur les métaux précieux', hubTitle: 'Votre portefeuille de métaux précieux. Une vue claire.', hubIntro: 'Des guides pratiques pour enregistrer, comprendre et organiser vos avoirs en or, argent et autres métaux précieux.', latestLabel: 'Guide récent', readLabel: 'Lire le guide', backLabel: 'Guides', homeLabel: 'Accueil', helpLabel: 'Aide', privacyLabel: 'Confidentialité', appLabel: 'Voir l’app', contentsLabel: 'Dans ce guide', relatedLabel: 'À découvrir aussi', faqLabel: 'Questions fréquentes', disclosure: 'MyGoldFolio fournit des outils de suivi, pas des conseils d’investissement, juridiques ou fiscaux.' },
  tr: { code: 'tr', locale: 'tr-TR', label: 'TR', hubPath: '/tr/rehber/', articlePath: '/tr/rehber/degerli-maden-portfoyu-takip/', hubLabel: 'Rehber', eyebrow: 'Değerli madenler için pratik bilgiler', hubTitle: 'Değerli maden portföyünüz. Net bir bakış.', hubIntro: 'Altın, gümüş ve diğer değerli maden varlıklarını kaydetmek, anlamak ve düzenlemek için pratik rehberler.', latestLabel: 'Yeni rehber', readLabel: 'Rehberi oku', backLabel: 'Rehber', homeLabel: 'Ana sayfa', helpLabel: 'Yardım', privacyLabel: 'Gizlilik', appLabel: 'Uygulamayı al', contentsLabel: 'Bu rehberde', relatedLabel: 'Daha fazlasını keşfet', faqLabel: 'Sık sorulan sorular', disclosure: 'MyGoldFolio takip araçları sunar; yatırım, hukuk veya vergi tavsiyesi vermez.' },
  es: { code: 'es', locale: 'es-ES', label: 'ES', hubPath: '/es/guias/', articlePath: '/es/guias/seguimiento-cartera-metales-preciosos/', hubLabel: 'Guías', eyebrow: 'Conocimiento práctico sobre metales preciosos', hubTitle: 'Tu cartera de metales preciosos. Todo claro.', hubIntro: 'Guías prácticas para registrar, entender y organizar tus posiciones de oro, plata y otros metales preciosos.', latestLabel: 'Guía reciente', readLabel: 'Leer la guía', backLabel: 'Guías', homeLabel: 'Inicio', helpLabel: 'Ayuda', privacyLabel: 'Privacidad', appLabel: 'Ver la app', contentsLabel: 'En esta guía', relatedLabel: 'Descubre más', faqLabel: 'Preguntas frecuentes', disclosure: 'MyGoldFolio ofrece herramientas de seguimiento, no asesoramiento de inversión, legal ni fiscal.' },
  it: { code: 'it', locale: 'it-IT', label: 'IT', hubPath: '/it/guide/', articlePath: '/it/guide/monitorare-portafoglio-metalli-preziosi/', hubLabel: 'Guide', eyebrow: 'Conoscenza pratica sui metalli preziosi', hubTitle: 'Il tuo portafoglio di metalli preziosi. Sempre chiaro.', hubIntro: 'Guide pratiche per registrare, capire e organizzare oro, argento e altri metalli preziosi.', latestLabel: 'Guida recente', readLabel: 'Leggi la guida', backLabel: 'Guide', homeLabel: 'Home', helpLabel: 'Aiuto', privacyLabel: 'Privacy', appLabel: 'Scopri l’app', contentsLabel: 'In questa guida', relatedLabel: 'Scopri anche', faqLabel: 'Domande frequenti', disclosure: 'MyGoldFolio offre strumenti di monitoraggio, non consulenza finanziaria, legale o fiscale.' },
  pt: { code: 'pt', locale: 'pt-BR', label: 'PT-BR', hubPath: '/pt/guias/', articlePath: '/pt/guias/acompanhar-carteira-metais-preciosos/', hubLabel: 'Guias', eyebrow: 'Conhecimento prático sobre metais preciosos', hubTitle: 'Sua carteira de metais preciosos. Tudo sob controle.', hubIntro: 'Guias práticos para registrar, entender e organizar ouro, prata e outros metais preciosos.', latestLabel: 'Guia recente', readLabel: 'Ler guia', backLabel: 'Guias', homeLabel: 'Início', helpLabel: 'Ajuda', privacyLabel: 'Privacidade', appLabel: 'Conheça o app', contentsLabel: 'Neste guia', relatedLabel: 'Veja também', faqLabel: 'Perguntas frequentes', disclosure: 'MyGoldFolio oferece ferramentas de acompanhamento, não aconselhamento de investimento, jurídico ou tributário.' }
};

export const article = {
  id: 'portfolio-tracking',
  published: '2026-08-08',
  updated: '2026-08-08',
  readingMinutes: 6,
  category: {
    en: 'Foundations', de: 'Grundlagen', fr: 'Fondamentaux', tr: 'Temeller', es: 'Conceptos básicos', it: 'Fondamenti', pt: 'Fundamentos'
  },
  image: '/images/articles/edelmetalle-portfolio-tracken-hero.png',
  imageAlt: {
    en: 'A paper ledger beside Gold and Silver bars', de: 'Ein Erfassungsblatt neben Gold- und Silberbarren', fr: 'Un registre papier à côté de lingots d’or et d’argent', tr: 'Altın ve gümüş külçelerin yanındaki kayıt defteri', es: 'Un registro en papel junto a lingotes de oro y plata', it: 'Un registro cartaceo accanto a lingotti d’oro e d’argento', pt: 'Um registro em papel ao lado de barras de ouro e prata'
  },
  locales: {
    en: {
      title: 'Track Precious Metals in Your Portfolio: App or Spreadsheet?',
      seoTitle: 'Precious Metals Portfolio Tracker: App or Spreadsheet?',
      description: 'Precious metals portfolio tracker for Gold and Silver: what spreadsheets do well, where they become difficult, and when an app is useful.',
      intro: 'Owning Gold and Silver is one thing. Keeping purchase prices, fine weights, and today’s picture understandable is another. Both methods work; the better choice is the one that fits your routine.',
      summary: 'For a few stable purchases, a spreadsheet can be enough. When positions, price checks, or possible sales become regular, a dedicated app mainly saves routine work—not thinking.',
      sections: [
        { id: 'record', title: 'What is worth recording', paragraphs: ['A precious-metals portfolio is more than one total. Record each purchase or lot clearly so you can still understand it later, whether it is a bar, coin, jewellery, or another physical holding.'], bullets: ['What you hold: metal, description, and purity where useful.', 'How much: quantity and fine weight, not only gross weight.', 'When you bought it: purchase date keeps the sequence and holding period clear.', 'What it really cost: total cost including premiums, delivery, and other fees.', 'Where it is stored: only a neutral note if useful; avoid sensitive details in an unprotected file.'] },
        { id: 'comparison', title: 'Spreadsheet and app: where each helps', table: { head: ['Task', 'Spreadsheet', 'Tracking app'], rows: [['Document individual purchases', 'Very flexible once columns are well designed.', 'Guided entries help keep positions consistent.'], ['See a current reference value', 'Needs a source, formulas, and regular maintenance.', 'Can keep reference prices and your cost basis side by side.'], ['Understand a position', 'Possible, but fees and partial sales quickly make formulas fragile.', 'Keeps purchases, costs, and scenarios close to the original position.'], ['Keep data private', 'Depends on file location, cloud sync, and backup habits.', 'Also depends on the product. MyGoldFolio keeps holdings on-device and lets you create your own export.']] } },
        { id: 'spreadsheet', title: 'When a spreadsheet is enough', paragraphs: ['A spreadsheet is a sound starting point when you hold only a few positions, buy or sell rarely, and are happy to maintain formulas yourself. It can also sit well beside invoices and other records.', 'Treat it as a maintained record rather than a one-off note: use clear columns, one weight convention, and a backup you control.'] },
        { id: 'app', title: 'When an app becomes useful', paragraphs: ['The benefit is rarely one number. It is the recurring questions: How is this exact purchase doing? What would a certain sale price mean? Which holding is closer to break-even? Did I include all costs?', 'A tracking app does not make the decision for you. It makes the information behind that decision easier to read. That structure becomes valuable with mixed Gold and Silver holdings, different purchase dates, or more than one display currency.'] },
        { id: 'decision', title: 'A simple way to decide', ordered: ['Will your holdings remain small and mostly unchanged? A spreadsheet may be sufficient.', 'Do you genuinely update prices regularly? If not, a spreadsheet’s current value becomes historical quickly.', 'Do you want to understand each purchase rather than only one total? Then position-based tracking helps.'] },
        { id: 'conclusion', title: 'The practical conclusion', paragraphs: ['A spreadsheet is flexible; an app is structured. There is no reason to replace a simple system that still serves you. When upkeep starts costing more time than it saves, dedicated tracking can bring clarity back.'] }
      ],
      ctaTitle: 'Keep Gold and Silver positions in view', ctaText: 'MyGoldFolio is a private, offline-first Android app for recording Gold and Silver holdings, reference values, scenarios, and alerts.', ctaLabel: 'View free on Google Play',
      faq: [{ q: 'Can I track precious metals with a spreadsheet?', a: 'Yes. For a few, rarely changed holdings, a carefully maintained spreadsheet can be enough. Use clear fields for metal, fine weight, purchase date, and total cost.' }, { q: 'What data should I record for Gold and Silver?', a: 'At minimum: metal, description, fine weight, purchase date, and total cost including fees. Purity, dealer, and sale records can also be useful.' }, { q: 'Is a tracking app investment advice?', a: 'No. It organizes existing data and supports your overview. It does not make buy or sell recommendations.' }]
    },
    de: {
      title: 'Edelmetalle im Portfolio tracken: App oder Spreadsheet?', seoTitle: 'Edelmetall-Tracker: App oder Spreadsheet fürs Portfolio?', description: 'Edelmetall-Tracker für Gold und Silber: Was Spreadsheets gut können, wann sie an Grenzen stoßen und wann eine Portfolio-App sinnvoll ist.', intro: 'Gold und Silber zu besitzen ist das eine. Den Überblick über Kaufpreise, Feingewichte und den heutigen Stand zu behalten, das andere. Beide Wege funktionieren – entscheidend ist, welcher zu deinem Alltag passt.', summary: 'Für wenige, selten veränderte Käufe kann ein Spreadsheet völlig genügen. Sobald mehrere Positionen, laufende Preise oder geplante Verkäufe dazukommen, spart eine spezialisierte App vor allem Routinearbeit – nicht Denkaufwand.',
      sections: [
        { id: 'record', title: 'Was du wirklich erfassen solltest', paragraphs: ['Ein Edelmetall-Portfolio ist mehr als eine Gesamtsumme. Erfasse Käufe oder Stückelungen eindeutig, damit später nachvollziehbar bleibt, was du besitzt und wie eine Position entstanden ist.'], bullets: ['Was: Metall, Bezeichnung und bei Bedarf Reinheit.', 'Wie viel: Stückzahl und Feingewicht – nicht nur das Bruttogewicht.', 'Wann: Kaufdatum, damit Reihenfolge und Haltedauer klar bleiben.', 'Zu welchem Gesamtpreis: Kaufpreis einschließlich Aufgeld, Versand und weiterer Nebenkosten.', 'Wo: Ein neutraler Hinweis zum Aufbewahrungsort, wenn er dir hilft. Keine sensiblen Details in eine ungeschützte Datei schreiben.'] },
        { id: 'comparison', title: 'Spreadsheet und App: wo beide helfen', table: { head: ['Aufgabe', 'Spreadsheet', 'Tracking-App'], rows: [['Einzelne Käufe dokumentieren', 'Sehr flexibel, wenn die Spalten einmal sauber angelegt sind.', 'Geführte Eingaben halten Positionen eher einheitlich.'], ['Aktuellen Referenzwert sehen', 'Benötigt Preisquelle, Formeln und regelmäßige Pflege.', 'Kann Referenzpreise und Anschaffungskosten direkt gegenüberstellen.'], ['Eine Position verstehen', 'Möglich, aber Gebühren und Teilverkäufe machen Formeln schnell fehleranfällig.', 'Hält Käufe, Kosten und Szenarien näher an der einzelnen Position.'], ['Daten privat halten', 'Hängt von Speicherort, Cloud-Sync und Backup-Disziplin ab.', 'Hängt ebenfalls vom Produkt ab. MyGoldFolio hält Bestände auf dem Gerät und bietet einen eigenen Export.']] } },
        { id: 'spreadsheet', title: 'Wann eine Tabelle reicht', paragraphs: ['Eine Tabelle ist ein guter Start, wenn du wenige Positionen hältst, selten kaufst oder verkaufst und Formeln gern selbst pflegst. Sie kann außerdem gut neben Belegen und Rechnungen bestehen.', 'Behandle sie als gepflegtes Verzeichnis statt als einmalige Notiz: nutze klare Spalten, eine Gewichtseinheit und ein Backup, das du kontrollierst.'] },
        { id: 'app', title: 'Wann eine App spürbar hilft', paragraphs: ['Der Nutzen liegt selten in einer einzelnen Zahl, sondern in wiederkehrenden Fragen: Wie entwickelt sich genau dieser Kauf? Was würde ein bestimmter Verkaufspreis bedeuten? Welche Position ist näher am Break-even? Sind alle Kosten erfasst?', 'Eine Tracking-App nimmt dir keine Entscheidung ab. Sie macht die Informationen dafür schneller lesbar. Diese Struktur wird bei gemischten Gold- und Silberbeständen, unterschiedlichen Kaufzeitpunkten oder mehreren Anzeigewährungen wertvoll.'] },
        { id: 'decision', title: 'Eine einfache Entscheidungshilfe', ordered: ['Bleibt dein Bestand klein und weitgehend unverändert? Dann reicht ein Spreadsheet oft aus.', 'Aktualisierst du Preise tatsächlich regelmäßig? Wenn nicht, wird der aktuelle Wert in der Tabelle schnell historisch.', 'Möchtest du einzelne Käufe statt nur eine Gesamtsumme verstehen? Dann hilft eine positionsbasierte Erfassung.'] },
        { id: 'conclusion', title: 'Das praktische Fazit', paragraphs: ['Ein Spreadsheet ist flexibel; eine App ist strukturiert. Es gibt keinen Grund, ein einfaches System zu ersetzen, das noch gut funktioniert. Wenn die Pflege mehr Zeit kostet als sie spart, kann spezialisiertes Tracking wieder Klarheit schaffen.'] }
      ], ctaTitle: 'Gold- und Silberpositionen im Blick behalten', ctaText: 'MyGoldFolio ist eine private, offline-first Android-App für Gold- und Silberbestände, Referenzwerte, Szenarien und Alarme.', ctaLabel: 'Kostenlos bei Google Play ansehen', faq: [{ q: 'Kann ich Edelmetalle auch mit einem Spreadsheet tracken?', a: 'Ja. Für wenige, selten veränderte Positionen kann eine gepflegte Tabelle ausreichen. Nutze klare Angaben zu Metall, Feingewicht, Kaufdatum und Gesamtkosten.' }, { q: 'Welche Daten sollte ich für Gold und Silber erfassen?', a: 'Mindestens Metall, Bezeichnung, Feingewicht, Kaufdatum und Gesamtkosten einschließlich Nebenkosten. Reinheit, Händler und Verkaufsdaten können ebenfalls sinnvoll sein.' }, { q: 'Ist eine Tracking-App Anlageberatung?', a: 'Nein. Sie organisiert vorhandene Daten und unterstützt deine Übersicht. Sie gibt keine Kauf- oder Verkaufsempfehlungen.' }]
    },
    fr: {
      title: 'Suivre ses métaux précieux : application ou tableur ?', description: 'Gardez vos positions en or et argent en vue : atouts du tableur, ses limites et le moment où une application de portefeuille devient utile.', intro: 'Posséder de l’or ou de l’argent est une chose. Garder clairement en vue les prix d’achat, les poids fins et la situation actuelle en est une autre. Les deux méthodes fonctionnent ; la bonne est celle qui convient à votre routine.', summary: 'Pour quelques achats stables, un tableur peut suffire. Quand les positions, vérifications de prix ou ventes possibles deviennent régulières, une application spécialisée réduit surtout le travail répétitif.',
      sections: [
        { id: 'record', title: 'Les informations qui méritent d’être enregistrées', paragraphs: ['Un portefeuille de métaux précieux ne se résume pas à un total. Enregistrez chaque achat ou lot clairement afin de pouvoir le comprendre plus tard, qu’il s’agisse d’un lingot, d’une pièce, d’un bijou ou d’un autre actif physique.'], bullets: ['Ce que vous détenez : métal, description et titre si utile.', 'La quantité : nombre de pièces et poids fin, pas seulement le poids brut.', 'La date : elle clarifie l’ordre et la durée de détention.', 'Le coût réel : prix total, primes, livraison et autres frais.', 'Le lieu : une note neutre si utile ; évitez les détails sensibles dans un fichier non protégé.'] },
        { id: 'comparison', title: 'Tableur et application : les points forts', table: { head: ['Tâche', 'Tableur', 'Application de suivi'], rows: [['Documenter les achats', 'Très souple une fois les colonnes bien conçues.', 'Les saisies guidées aident à garder des positions cohérentes.'], ['Voir une valeur de référence', 'Nécessite une source, des formules et un entretien régulier.', 'Peut rapprocher prix de référence et coût d’acquisition.'], ['Comprendre une position', 'Possible, mais les frais et ventes partielles fragilisent vite les formules.', 'Garde achats, coûts et scénarios près de la position.'], ['Garder ses données privées', 'Dépend du stockage, de la synchronisation et des sauvegardes.', 'Dépend aussi du produit. MyGoldFolio conserve les positions sur l’appareil et permet un export personnel.']] } },
        { id: 'spreadsheet', title: 'Quand un tableur suffit', paragraphs: ['Un tableur est un bon point de départ si vous avez peu de positions, achetez ou vendez rarement et aimez entretenir vous-même vos formules. Il accompagne aussi très bien factures et justificatifs.', 'Considérez-le comme un registre à maintenir : colonnes claires, unité de poids cohérente et sauvegarde que vous maîtrisez.'] },
        { id: 'app', title: 'Quand une application devient utile', paragraphs: ['L’intérêt n’est souvent pas un seul chiffre, mais des questions récurrentes : comment évolue précisément cet achat ? Que signifierait un prix de vente donné ? Quelle position est la plus proche du seuil de rentabilité ? Tous les coûts sont-ils saisis ?', 'Une application ne décide pas à votre place. Elle rend les informations plus lisibles, surtout avec des positions mixtes en or et argent, des dates d’achat différentes ou plusieurs devises d’affichage.'] },
        { id: 'decision', title: 'Une façon simple de décider', ordered: ['Vos positions resteront-elles peu nombreuses et stables ? Un tableur peut suffire.', 'Mettez-vous réellement les prix à jour régulièrement ? Sinon, sa valeur actuelle vieillit vite.', 'Souhaitez-vous comprendre chaque achat, pas seulement un total ? Un suivi par position aide.'] },
        { id: 'conclusion', title: 'Conclusion pratique', paragraphs: ['Le tableur est flexible ; l’application est structurée. Inutile de remplacer un système simple qui vous sert encore. Quand son entretien prend plus de temps qu’il n’en fait gagner, un suivi spécialisé peut redonner de la clarté.'] }
      ], ctaTitle: 'Gardez vos positions en or et argent en vue', ctaText: 'MyGoldFolio est une application Android privée, pensée hors ligne, pour enregistrer des positions en or et argent, des valeurs de référence, des scénarios et des alertes.', ctaLabel: 'Voir gratuitement sur Google Play', faq: [{ q: 'Puis-je suivre mes métaux précieux avec un tableur ?', a: 'Oui. Pour quelques positions rarement modifiées, un tableur soigneusement entretenu peut suffire.' }, { q: 'Quelles données enregistrer pour l’or et l’argent ?', a: 'Au minimum le métal, la description, le poids fin, la date d’achat et le coût total frais compris.' }, { q: 'Une application de suivi est-elle un conseil en investissement ?', a: 'Non. Elle organise des données existantes et ne formule pas de recommandations d’achat ou de vente.' }]
    },
    tr: {
      title: 'Değerli maden portföyü nasıl takip edilir: uygulama mı, tablo mu?', description: 'Altın ve gümüş varlıklarınızı takip edin: tabloların güçlü yanları, sınırları ve portföy uygulamasının ne zaman faydalı olduğu.', intro: 'Altın ve gümüşe sahip olmak bir şeydir. Alış fiyatlarını, saf ağırlıkları ve güncel durumu anlaşılır tutmak başka bir şeydir. Her iki yöntem de işe yarar; doğru seçim günlük düzeninize uyan seçimdir.', summary: 'Az sayıda ve nadiren değişen alım için tablo yeterli olabilir. Pozisyonlar, fiyat kontrolleri veya olası satışlar düzenli hâle geldiğinde, özel bir uygulama esas olarak tekrar eden işi azaltır.',
      sections: [
        { id: 'record', title: 'Kaydetmeye değer bilgiler', paragraphs: ['Bir değerli maden portföyü tek bir toplamdan fazlasıdır. Külçe, sikke, mücevher veya başka bir fiziksel varlık olsun, her alımı ya da partiyi daha sonra anlayabileceğiniz şekilde kaydedin.'], bullets: ['Ne tuttuğunuz: metal, açıklama ve gerekirse saflık.', 'Ne kadar: adet ve saf ağırlık; yalnızca brüt ağırlık değil.', 'Ne zaman: alış tarihi sıralamayı ve elde tutma süresini açık tutar.', 'Gerçek maliyet: toplam alış bedeli, prim, teslimat ve diğer ücretler.', 'Nerede: faydalıysa nötr bir not; korunmayan dosyalara hassas ayrıntılar yazmayın.'] },
        { id: 'comparison', title: 'Tablo ve uygulama: her birinin gücü', table: { head: ['Görev', 'Tablo', 'Takip uygulaması'], rows: [['Alımları belgelemek', 'Sütunlar düzgün kurulduğunda çok esnektir.', 'Yönlendirilmiş girişler pozisyonları tutarlı tutar.'], ['Güncel referans değer görmek', 'Kaynak, formül ve düzenli bakım gerektirir.', 'Referans fiyatları ve maliyeti yan yana tutabilir.'], ['Bir pozisyonu anlamak', 'Mümkündür; fakat ücretler ve kısmi satışlar formülleri kırılganlaştırır.', 'Alım, maliyet ve senaryoları pozisyona yakın tutar.'], ['Veriyi gizli tutmak', 'Dosya konumu, bulut senkronizasyonu ve yedek alışkanlığına bağlıdır.', 'Ürüne de bağlıdır. MyGoldFolio varlıkları cihazda tutar ve kişisel dışa aktarma sunar.']] } },
        { id: 'spreadsheet', title: 'Tablo ne zaman yeterlidir?', paragraphs: ['Az sayıda pozisyonunuz varsa, nadiren alım satım yapıyorsanız ve formülleri kendiniz sürdürmekten memnunsanız tablo iyi bir başlangıçtır. Fatura ve belgelerin yanında da iyi çalışır.', 'Onu tek seferlik not değil, düzenli kayıt olarak görün: açık sütunlar, tutarlı ağırlık birimi ve kontrolünüzde bir yedek kullanın.'] },
        { id: 'app', title: 'Uygulama ne zaman fayda sağlar?', paragraphs: ['Fayda çoğu zaman tek bir sayı değildir; tekrarlanan sorulardır: Bu alım nasıl gidiyor? Belirli bir satış fiyatı ne anlama gelir? Hangi pozisyon başa başa daha yakın? Tüm masraflar kaydedildi mi?', 'Takip uygulaması sizin yerinize karar vermez. Kararın arkasındaki bilgiyi daha okunur yapar. Bu yapı, karışık altın-gümüş varlıklarında, farklı alış tarihlerinde veya birden fazla görüntüleme para biriminde değer kazanır.'] },
        { id: 'decision', title: 'Basit karar yardımı', ordered: ['Varlıklarınız küçük ve büyük ölçüde değişmeden mi kalacak? Tablo yeterli olabilir.', 'Fiyatları gerçekten düzenli güncelliyor musunuz? Güncellemiyorsanız güncel değer hızla eski kalır.', 'Yalnızca toplamı değil, her alımı anlamak istiyor musunuz? Pozisyon bazlı takip yardımcı olur.'] },
        { id: 'conclusion', title: 'Pratik sonuç', paragraphs: ['Tablo esnektir; uygulama yapılandırılmıştır. Hâlâ işe yarayan basit bir sistemi değiştirmek için neden yoktur. Bakım, kazandırdığından fazla zaman almaya başladığında özel takip yeniden netlik sağlayabilir.'] }
      ], ctaTitle: 'Altın ve gümüş pozisyonlarını görünür tutun', ctaText: 'MyGoldFolio; altın ve gümüş varlıkları, referans değerleri, senaryolar ve alarmlar için özel, offline-first bir Android uygulamasıdır.', ctaLabel: 'Google Play’de ücretsiz görüntüle', faq: [{ q: 'Değerli madenleri tabloyla takip edebilir miyim?', a: 'Evet. Az sayıda ve nadiren değişen pozisyon için düzenli tutulan tablo yeterli olabilir.' }, { q: 'Altın ve gümüş için hangi verileri kaydetmeliyim?', a: 'En az metal, açıklama, saf ağırlık, alış tarihi ve ücretler dâhil toplam maliyet.' }, { q: 'Takip uygulaması yatırım tavsiyesi midir?', a: 'Hayır. Mevcut verileri düzenler ve alım ya da satım önerisi vermez.' }]
    },
    es: {
      title: 'Cómo seguir tu cartera de metales preciosos: ¿app u hoja de cálculo?', description: 'Mantén a la vista tus posiciones de oro y plata: qué hace bien una hoja de cálculo, dónde se complica y cuándo ayuda una app de cartera.', intro: 'Tener oro y plata es una cosa. Mantener claros los precios de compra, los pesos finos y la situación actual es otra. Ambos métodos funcionan; el mejor es el que encaja con tu rutina.', summary: 'Para pocas compras estables, una hoja de cálculo puede bastar. Cuando las posiciones, revisiones de precio o posibles ventas son habituales, una app especializada reduce sobre todo el trabajo repetitivo.',
      sections: [
        { id: 'record', title: 'Qué conviene registrar', paragraphs: ['Una cartera de metales preciosos es más que un total. Registra cada compra o lote con claridad para poder entenderlo más adelante, ya sea una barra, moneda, joya u otra posición física.'], bullets: ['Qué tienes: metal, descripción y pureza cuando sea útil.', 'Cuánto: unidades y peso fino, no solo peso bruto.', 'Cuándo lo compraste: la fecha aclara el orden y el periodo de tenencia.', 'Coste real: precio total, primas, envío y otros gastos.', 'Dónde se guarda: solo una nota neutral si aporta valor; evita detalles sensibles en archivos sin protección.'] },
        { id: 'comparison', title: 'Hoja de cálculo y app: dónde ayuda cada una', table: { head: ['Tarea', 'Hoja de cálculo', 'App de seguimiento'], rows: [['Documentar compras', 'Muy flexible cuando las columnas están bien diseñadas.', 'Las entradas guiadas ayudan a mantener posiciones coherentes.'], ['Ver un valor de referencia actual', 'Requiere una fuente, fórmulas y mantenimiento regular.', 'Puede mantener juntos precios de referencia y coste de compra.'], ['Entender una posición', 'Es posible, pero gastos y ventas parciales vuelven frágiles las fórmulas.', 'Mantiene compras, costes y escenarios cerca de la posición.'], ['Mantener los datos privados', 'Depende de la ubicación, sincronización en nube y copias de seguridad.', 'También depende del producto. MyGoldFolio conserva posiciones en el dispositivo y permite exportación propia.']] } },
        { id: 'spreadsheet', title: 'Cuándo basta una hoja de cálculo', paragraphs: ['Es un buen inicio si tienes pocas posiciones, compras o vendes poco y te gusta mantener tus propias fórmulas. También puede convivir bien con facturas y comprobantes.', 'Trátala como un registro vivo: columnas claras, una unidad de peso coherente y una copia de seguridad bajo tu control.'] },
        { id: 'app', title: 'Cuándo una app ayuda de verdad', paragraphs: ['El beneficio rara vez es una cifra aislada, sino preguntas recurrentes: ¿cómo va exactamente esta compra? ¿Qué significaría cierto precio de venta? ¿Qué posición está más cerca del punto de equilibrio? ¿Incluí todos los costes?', 'Una app no decide por ti. Hace más legible la información que necesitas para decidir. Esa estructura ayuda con posiciones mixtas de oro y plata, fechas de compra distintas o más de una moneda de visualización.'] },
        { id: 'decision', title: 'Una forma sencilla de decidir', ordered: ['¿Tus posiciones seguirán siendo pocas y estables? Una hoja puede ser suficiente.', '¿Actualizas realmente los precios con frecuencia? Si no, el valor actual envejece rápido.', '¿Quieres entender cada compra y no solo un total? El seguimiento por posición ayuda.'] },
        { id: 'conclusion', title: 'Conclusión práctica', paragraphs: ['La hoja de cálculo es flexible; la app es estructurada. No hace falta sustituir un sistema simple que aún funciona. Cuando su mantenimiento cuesta más tiempo del que ahorra, un seguimiento especializado puede devolver claridad.'] }
      ], ctaTitle: 'Mantén a la vista tus posiciones de oro y plata', ctaText: 'MyGoldFolio es una app Android privada y offline-first para posiciones de oro y plata, valores de referencia, escenarios y alertas.', ctaLabel: 'Ver gratis en Google Play', faq: [{ q: '¿Puedo seguir metales preciosos con una hoja de cálculo?', a: 'Sí. Para pocas posiciones que cambian poco, una hoja bien mantenida puede bastar.' }, { q: '¿Qué datos debo registrar para oro y plata?', a: 'Como mínimo metal, descripción, peso fino, fecha de compra y coste total incluidos los gastos.' }, { q: '¿Una app de seguimiento es asesoramiento de inversión?', a: 'No. Organiza datos existentes y no hace recomendaciones de compra o venta.' }]
    },
    it: {
      title: 'Come monitorare il portafoglio di metalli preziosi: app o foglio di calcolo?', description: 'Tieni sotto controllo oro e argento: cosa fa bene un foglio di calcolo, dove diventa complesso e quando è utile un’app di portafoglio.', intro: 'Possedere oro e argento è una cosa. Mantenere chiari prezzi di acquisto, pesi fini e situazione attuale è un’altra. Entrambi i metodi funzionano; il migliore è quello adatto alla tua routine.', summary: 'Per pochi acquisti stabili può bastare un foglio di calcolo. Quando posizioni, controlli dei prezzi o possibili vendite diventano ricorrenti, un’app specializzata riduce soprattutto il lavoro ripetitivo.',
      sections: [
        { id: 'record', title: 'Cosa vale la pena registrare', paragraphs: ['Un portafoglio di metalli preziosi è più di un totale. Registra con chiarezza ogni acquisto o lotto per poterlo capire anche in futuro, che si tratti di lingotti, monete, gioielli o altre posizioni fisiche.'], bullets: ['Cosa possiedi: metallo, descrizione e purezza quando utile.', 'Quanto: quantità e peso fino, non solo peso lordo.', 'Quando hai acquistato: la data chiarisce ordine e durata di possesso.', 'Costo reale: prezzo totale, premi, consegna e altre spese.', 'Dove è custodito: solo una nota neutra se utile; evita dettagli sensibili in file non protetti.'] },
        { id: 'comparison', title: 'Foglio e app: dove aiutano', table: { head: ['Attività', 'Foglio di calcolo', 'App di monitoraggio'], rows: [['Documentare acquisti', 'Molto flessibile quando le colonne sono progettate bene.', 'Gli inserimenti guidati aiutano a mantenere posizioni coerenti.'], ['Vedere un valore di riferimento', 'Richiede fonte, formule e manutenzione regolare.', 'Può tenere affiancati prezzi di riferimento e costo di acquisto.'], ['Capire una posizione', 'Possibile, ma spese e vendite parziali rendono presto fragili le formule.', 'Mantiene acquisti, costi e scenari vicini alla posizione.'], ['Mantenere privati i dati', 'Dipende da posizione del file, cloud e abitudini di backup.', 'Dipende anche dal prodotto. MyGoldFolio conserva le posizioni sul dispositivo e consente un export personale.']] } },
        { id: 'spreadsheet', title: 'Quando basta un foglio di calcolo', paragraphs: ['È un buon punto di partenza se hai poche posizioni, compri o vendi raramente e preferisci gestire le formule da solo. Può convivere bene con fatture e documenti.', 'Trattalo come un registro da mantenere: colonne chiare, un’unità di peso coerente e un backup sotto il tuo controllo.'] },
        { id: 'app', title: 'Quando un’app diventa utile', paragraphs: ['Il vantaggio raramente è un solo numero, ma domande ricorrenti: come sta andando esattamente questo acquisto? Cosa significherebbe un certo prezzo di vendita? Quale posizione è più vicina al pareggio? Ho inserito tutti i costi?', 'Un’app non decide al posto tuo. Rende più leggibili le informazioni necessarie per decidere. Questa struttura aiuta con posizioni miste in oro e argento, date di acquisto diverse o più valute di visualizzazione.'] },
        { id: 'decision', title: 'Un modo semplice per decidere', ordered: ['Le tue posizioni resteranno poche e stabili? Un foglio può bastare.', 'Aggiorni davvero i prezzi con regolarità? Altrimenti il valore attuale invecchia rapidamente.', 'Vuoi capire ogni acquisto e non solo un totale? Il monitoraggio per posizione aiuta.'] },
        { id: 'conclusion', title: 'Conclusione pratica', paragraphs: ['Il foglio di calcolo è flessibile; l’app è strutturata. Non serve sostituire un sistema semplice che funziona ancora. Quando la manutenzione costa più tempo di quanto ne risparmia, un monitoraggio specializzato può riportare chiarezza.'] }
      ], ctaTitle: 'Tieni in vista le posizioni in oro e argento', ctaText: 'MyGoldFolio è un’app Android privata, offline-first, per posizioni in oro e argento, valori di riferimento, scenari e avvisi.', ctaLabel: 'Scopri gratis su Google Play', faq: [{ q: 'Posso monitorare i metalli preziosi con un foglio di calcolo?', a: 'Sì. Per poche posizioni che cambiano raramente, un foglio ben mantenuto può bastare.' }, { q: 'Quali dati devo registrare per oro e argento?', a: 'Al minimo metallo, descrizione, peso fino, data di acquisto e costo totale compresi gli oneri.' }, { q: 'Un’app di monitoraggio è consulenza finanziaria?', a: 'No. Organizza dati esistenti e non formula raccomandazioni di acquisto o vendita.' }]
    },
    pt: {
      title: 'Como acompanhar sua carteira de metais preciosos: app ou planilha?', description: 'Mantenha ouro e prata sob controle: o que uma planilha faz bem, onde ela fica complexa e quando um app de carteira ajuda.', intro: 'Possuir ouro e prata é uma coisa. Manter claros os preços de compra, pesos finos e a situação atual é outra. Os dois métodos funcionam; o melhor é o que se encaixa na sua rotina.', summary: 'Para poucas compras estáveis, uma planilha pode bastar. Quando posições, conferências de preço ou possíveis vendas se tornam frequentes, um app especializado reduz principalmente o trabalho repetitivo.',
      sections: [
        { id: 'record', title: 'O que vale registrar', paragraphs: ['Uma carteira de metais preciosos é mais do que um total. Registre cada compra ou lote com clareza para conseguir entendê-lo depois, seja barra, moeda, joia ou outra posição física.'], bullets: ['O que você possui: metal, descrição e pureza quando útil.', 'Quanto: quantidade e peso fino, não apenas peso bruto.', 'Quando comprou: a data esclarece a ordem e o período de posse.', 'Custo real: preço total, ágio, entrega e outras taxas.', 'Onde está guardado: apenas uma observação neutra se ajudar; evite detalhes sensíveis em arquivos desprotegidos.'] },
        { id: 'comparison', title: 'Planilha e app: onde cada um ajuda', table: { head: ['Tarefa', 'Planilha', 'App de acompanhamento'], rows: [['Documentar compras', 'Muito flexível quando as colunas são bem estruturadas.', 'Entradas guiadas ajudam a manter posições consistentes.'], ['Ver um valor de referência atual', 'Exige fonte, fórmulas e manutenção regular.', 'Pode manter preços de referência e custo de compra lado a lado.'], ['Entender uma posição', 'É possível, mas taxas e vendas parciais tornam fórmulas frágeis.', 'Mantém compras, custos e cenários perto da posição.'], ['Manter os dados privados', 'Depende do local do arquivo, nuvem e hábitos de backup.', 'Também depende do produto. MyGoldFolio mantém posições no dispositivo e permite exportação própria.']] } },
        { id: 'spreadsheet', title: 'Quando uma planilha basta', paragraphs: ['É um bom começo se você tem poucas posições, compra ou vende raramente e gosta de manter suas próprias fórmulas. Ela também pode ficar ao lado de notas fiscais e comprovantes.', 'Trate-a como um registro vivo: colunas claras, uma unidade de peso consistente e um backup sob seu controle.'] },
        { id: 'app', title: 'Quando um app ajuda de verdade', paragraphs: ['O benefício raramente é um número isolado, mas perguntas recorrentes: como está exatamente esta compra? O que certo preço de venda significaria? Qual posição está mais perto do ponto de equilíbrio? Registrei todos os custos?', 'Um app não decide por você. Ele torna mais legíveis as informações por trás da decisão. Essa estrutura ajuda com posições mistas de ouro e prata, datas de compra diferentes ou mais de uma moeda de exibição.'] },
        { id: 'decision', title: 'Uma forma simples de decidir', ordered: ['Suas posições continuarão pequenas e estáveis? Uma planilha pode ser suficiente.', 'Você realmente atualiza preços com frequência? Caso contrário, o valor atual envelhece rápido.', 'Quer entender cada compra, e não somente um total? O acompanhamento por posição ajuda.'] },
        { id: 'conclusion', title: 'Conclusão prática', paragraphs: ['A planilha é flexível; o app é estruturado. Não há motivo para trocar um sistema simples que ainda funciona. Quando a manutenção custa mais tempo do que economiza, um acompanhamento especializado pode trazer clareza de volta.'] }
      ], ctaTitle: 'Mantenha posições de ouro e prata à vista', ctaText: 'MyGoldFolio é um app Android privado, offline-first, para posições de ouro e prata, valores de referência, cenários e alertas.', ctaLabel: 'Ver grátis no Google Play', faq: [{ q: 'Posso acompanhar metais preciosos em uma planilha?', a: 'Sim. Para poucas posições que mudam raramente, uma planilha bem mantida pode bastar.' }, { q: 'Quais dados devo registrar para ouro e prata?', a: 'No mínimo metal, descrição, peso fino, data de compra e custo total incluindo taxas.' }, { q: 'Um app de acompanhamento é aconselhamento de investimento?', a: 'Não. Ele organiza dados existentes e não faz recomendações de compra ou venda.' }]
    }
  }
};

// These questions address the practical hesitation behind adopting a tracker.
// They intentionally replace generic product FAQ copy on every localized equivalent.
Object.assign(article.locales.en, { faq: [
  { q: 'Is it worth setting up an app and entering my existing holdings?', a: 'Yes, if you want more than one total. Once each item is recorded, you can see the overall portfolio and how individual purchases are doing, filter positions, explore scenarios, and set watches or alerts. You configure it once, then let it keep watch; holdings remain private on your phone.' },
  { q: 'Do I need to keep prices and calculations up to date by hand?', a: 'No formulas need rebuilding. MyGoldFolio uses current reference-price updates for valuation and can watch the price conditions you choose. You only add or change your own transaction details when something in your portfolio changes.' },
  { q: 'Are my portfolio details private, and can I move them to another phone?', a: 'Your holdings stay on your device; there is no portfolio account or server copy. Export a backup when you choose, then import it on another device. That gives you control, but also means you should keep a safe backup.' }
] });
Object.assign(article.locales.de, { faq: [
  { q: 'Lohnt es sich, eine App einzurichten und vorhandene Bestände einzutragen?', a: 'Ja, wenn du mehr als eine Gesamtsumme sehen möchtest. Nach dem Eintragen zeigt dir die App Gesamtportfolio und einzelne Käufe, erlaubt Filter und Szenarien und kann Watches oder Alarme setzen. Du richtest es einmal ein; danach behält die App den Überblick – privat auf deinem Handy.' },
  { q: 'Muss ich Preise und Berechnungen weiter von Hand pflegen?', a: 'Du musst keine Formeln neu bauen. MyGoldFolio nutzt aktuelle Referenzpreis-Updates für die Bewertung und kann die Preisbedingungen beobachten, die du auswählst. Deine eigenen Kauf- oder Verkaufsdaten passt du nur an, wenn sich im Portfolio etwas ändert.' },
  { q: 'Bleiben meine Portfoliodaten privat und kann ich sie auf ein neues Handy umziehen?', a: 'Deine Bestände bleiben auf deinem Gerät; es gibt kein Portfolio-Konto und keine Serverkopie. Du kannst selbst ein Backup exportieren und es auf einem anderen Gerät importieren. Das gibt dir Kontrolle – deshalb solltest du das Backup sicher aufbewahren.' }
] });
Object.assign(article.locales.fr, { faq: [
  { q: 'Est-ce utile de configurer une application et d’y saisir mes positions existantes ?', a: 'Oui, si vous souhaitez plus qu’un total. Une fois chaque élément saisi, vous voyez le portefeuille global et chaque achat, filtrez les positions, explorez des scénarios et créez des suivis ou alertes. Vous configurez une fois ; l’application garde ensuite un œil sur vos données, privées sur votre téléphone.' },
  { q: 'Dois-je mettre à jour les prix et calculs manuellement ?', a: 'Vous n’avez pas de formules à reconstruire. MyGoldFolio utilise des mises à jour de prix de référence pour l’évaluation et peut surveiller les conditions de prix choisies. Vous modifiez seulement vos propres opérations lorsqu’un élément du portefeuille change.' },
  { q: 'Mes données restent-elles privées et puis-je les transférer vers un autre téléphone ?', a: 'Vos positions restent sur votre appareil ; il n’existe ni compte de portefeuille ni copie serveur. Vous pouvez exporter une sauvegarde puis l’importer sur un autre appareil. Vous gardez ainsi le contrôle, mais devez conserver cette sauvegarde en lieu sûr.' }
] });
Object.assign(article.locales.tr, { faq: [
  { q: 'Bir uygulama kurup mevcut varlıklarımı girmek gerçekten değer mi?', a: 'Toplam rakamdan fazlasını görmek istiyorsanız evet. Her öğeyi girdikten sonra toplam portföyü ve tek tek alımları görebilir, pozisyonları filtreleyebilir, senaryoları inceleyebilir, takip ve alarm kurabilirsiniz. Bir kez ayarlarsınız; uygulama daha sonra telefonunuzdaki özel verileri izler.' },
  { q: 'Fiyatları ve hesaplamaları elle güncellemem gerekir mi?', a: 'Formülleri yeniden kurmanız gerekmez. MyGoldFolio değerleme için güncel referans fiyatı güncellemelerini kullanır ve seçtiğiniz fiyat koşullarını izleyebilir. Kendi işlem ayrıntılarınızı yalnızca portföyünüz değiştiğinde güncellersiniz.' },
  { q: 'Portföy verilerim gizli kalır mı ve başka telefona taşıyabilir miyim?', a: 'Varlıklarınız cihazınızda kalır; portföy hesabı veya sunucu kopyası yoktur. İstediğiniz zaman yedek dışa aktarabilir ve başka cihazda içe aktarabilirsiniz. Kontrol sizdedir; bu nedenle yedeği güvenli saklamalısınız.' }
] });
Object.assign(article.locales.es, { faq: [
  { q: '¿Merece la pena configurar una app e introducir mis posiciones actuales?', a: 'Sí, si quieres ver más que un total. Cuando registras cada elemento, ves la cartera global y cada compra, puedes filtrar posiciones, explorar escenarios y crear seguimientos o alertas. La configuras una vez y después la app vigila tus datos, privados en tu teléfono.' },
  { q: '¿Tengo que actualizar precios y cálculos manualmente?', a: 'No necesitas reconstruir fórmulas. MyGoldFolio utiliza actualizaciones de precios de referencia para la valoración y puede vigilar las condiciones de precio que elijas. Solo actualizas los detalles de tus operaciones cuando cambia algo en tu cartera.' },
  { q: '¿Mis datos siguen siendo privados y puedo moverlos a otro teléfono?', a: 'Tus posiciones permanecen en tu dispositivo; no hay cuenta de cartera ni copia en servidor. Puedes exportar una copia de seguridad e importarla en otro dispositivo. Conservas el control, pero debes guardar esa copia de forma segura.' }
] });
Object.assign(article.locales.it, { faq: [
  { q: 'Vale la pena configurare un’app e inserire le mie posizioni attuali?', a: 'Sì, se vuoi vedere più di un totale. Dopo aver inserito ogni elemento puoi vedere il portafoglio complessivo e i singoli acquisti, filtrare le posizioni, esplorare scenari e creare controlli o avvisi. Configuri una volta e l’app continua a monitorare dati privati sul tuo telefono.' },
  { q: 'Devo aggiornare a mano prezzi e calcoli?', a: 'Non devi ricostruire formule. MyGoldFolio usa aggiornamenti dei prezzi di riferimento per la valutazione e può monitorare le condizioni di prezzo che scegli. Aggiorni i dettagli delle tue operazioni solo quando il portafoglio cambia.' },
  { q: 'I miei dati restano privati e posso spostarli su un altro telefono?', a: 'Le posizioni restano sul dispositivo; non esistono un account di portafoglio o una copia sul server. Puoi esportare un backup e importarlo su un altro dispositivo. Mantieni il controllo, ma devi conservare il backup in modo sicuro.' }
] });
Object.assign(article.locales.pt, { faq: [
  { q: 'Vale a pena configurar um app e incluir minhas posições atuais?', a: 'Sim, se você quer ver mais do que um total. Depois de registrar cada item, você vê a carteira geral e cada compra, filtra posições, explora cenários e cria acompanhamentos ou alertas. Você configura uma vez e o app continua observando dados privados no seu celular.' },
  { q: 'Preciso atualizar preços e cálculos manualmente?', a: 'Não é preciso reconstruir fórmulas. MyGoldFolio usa atualizações de preços de referência para a avaliação e pode acompanhar as condições de preço que você escolher. Você só atualiza os detalhes das próprias operações quando algo muda na carteira.' },
  { q: 'Meus dados ficam privados e posso movê-los para outro celular?', a: 'Suas posições ficam no dispositivo; não há conta de carteira nem cópia em servidor. Você pode exportar um backup e importá-lo em outro dispositivo. Isso mantém o controle com você, mas exige guardar o backup com segurança.' }
] });
